import { useMemo, useRef, useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { ChevronDown, ChevronUp, Calendar as CalendarIcon, Clock, Bell, Trash2, Eye, Download, Upload, FileText, X, Loader2, Plus, Archive, ArchiveRestore } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog';
import { format, parseISO, addMonths } from 'date-fns';
import { fr } from 'date-fns/locale';
import { useUpdateContract, useDeleteContract, isContractRenewingSoon, getMonthsUntilRenewal, useContractProposalRent, useContractProposalOptions, useContractProposalOperationalContact, Contract, ContractExternalProvider, PaymentFrequency } from '@/hooks/useContracts';
import { getOptionPriceLabel } from '@/lib/options-price-utils';
import { generateAndUploadServiceContractPdf } from '@/lib/service-contract-generator';
import { generateServiceContractNumber } from '@/lib/contract-numbering';
import { calculateLoyerTrimestriel } from '@/lib/rental-calculations';
import { useCommerciaux } from '@/hooks/useCommerciaux';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';
import { useAuth } from '@/hooks/useAuth';
import { ServiceReferencesPanel, useServiceReferences } from '@/components/technician-tracking/ServiceReferencesPanel';


const FINANCIAL_PARTNERS = ['Lixxbail 1', 'Lixxbail 2', 'Grenke 1', 'Franfinance 1', 'Olinn 1', 'Olinn 2', 'BNP VR 2', 'BNP Crédit Bail 1', 'Realease 2'];
const DURATIONS = [12, 24, 36, 48, 60];
const MAX_ATTACHMENT_SIZE = 20 * 1024 * 1024;

function sanitizeFileName(name: string) {
  return name.replace(/[^a-zA-Z0-9._-]/g, '_').slice(0, 80);
}

function uid() {
  return Math.random().toString(36).substring(2, 9);
}

function normalizeExternalProviders(value: unknown): ContractExternalProvider[] {
  if (!Array.isArray(value)) return [];
  return value
    .filter((provider) => provider && typeof provider === 'object')
    .map((provider, index) => {
      const p = provider as ContractExternalProvider;
      return {
        id: typeof p.id === 'string' && p.id ? p.id : `provider-${index}-${uid()}`,
        name: typeof p.name === 'string' ? p.name : '',
        role: typeof p.role === 'string' ? p.role : '',
        contact: typeof p.contact === 'string' ? p.contact : '',
        phone: typeof p.phone === 'string' ? p.phone : '',
        email: typeof p.email === 'string' ? p.email : '',
      };
    });
}

export function ContractRow({ contract, onVisualize, defaultExpanded = false, hideFinancialPartner = false, onPlanIntervention }: { contract: Contract; onVisualize?: (contract: Contract) => void; defaultExpanded?: boolean; hideFinancialPartner?: boolean; onPlanIntervention?: (p: { reference_id: string; contract_id: string }) => void }) {
  const [expanded, setExpanded] = useState(defaultExpanded);
  const updateContract = useUpdateContract();
  const deleteContract = useDeleteContract();
  const queryClient = useQueryClient();
  const { commerciaux } = useCommerciaux();
  const { isAdmin, isTechnicien } = useAuth();
  const canEditContract = isAdmin;
  const { data: allServiceRefs } = useServiceReferences();
  const serviceRefs = useMemo(
    () => (allServiceRefs ?? []).filter((r) => r.contract_id === contract.id),
    [allServiceRefs, contract.id],
  );
  const { toast } = useToast();
  const fileInputRef = useRef<HTMLInputElement>(null);


  const isQuick = !!contract.is_quick_contract;
  const isServiceContract = contract.proposal_type === 'service';
  const isClosed = !!contract.closed_at;
  const [attachmentState, setAttachmentState] = useState<{ url: string | null; name: string | null } | null>(null);
  const attachmentUrl = attachmentState ? attachmentState.url : contract.attachment_url ?? null;
  const attachmentName = attachmentState ? attachmentState.name : contract.attachment_name ?? null;
  const isLegacyAutoGeneratedServicePdf = isServiceContract && !!attachmentName && attachmentName.startsWith('Contrat_Services_');
  const canReuseAttachment = !!attachmentUrl && !isLegacyAutoGeneratedServicePdf;

  const renewing = isContractRenewingSoon(contract);
  const monthsLeft = getMonthsUntilRenewal(contract);

  const [clientName, setClientName] = useState(contract.client_name ?? '');
  const [implementationDate, setImplementationDate] = useState<Date | undefined>(
    contract.implementation_month ? parseISO(contract.implementation_month) : undefined
  );
  const [financialPartner, setFinancialPartner] = useState(contract.financial_partner ?? '');
  const [durationMonths, setDurationMonths] = useState(
    contract.duration_months ? String(contract.duration_months) : ''
  );
  const [paymentFrequency, setPaymentFrequency] = useState<PaymentFrequency>(
    contract.payment_frequency ?? 'mensuel'
  );
  const [commercialId, setCommercialId] = useState(contract.commercial_id ?? '');
  const [contractNumber, setContractNumber] = useState(contract.contract_number ?? '');
  const [erpReference, setErpReference] = useState(contract.erp_reference ?? '');
  const [cessionPercent, setCessionPercent] = useState<number | null>(contract.cession_percent ?? null);
  const [externalProviders, setExternalProviders] = useState<ContractExternalProvider[]>(() => normalizeExternalProviders(contract.external_providers));
  const { data: proposalRent } = useContractProposalRent(isQuick ? null : contract.proposal_id);
  const { data: proposalOptions } = useContractProposalOptions(isQuick ? null : contract.proposal_id);
  const { data: proposalOpContact } = useContractProposalOperationalContact(
    isQuick || !isServiceContract ? null : contract.proposal_id,
  );

  // Fallback saisi manuellement (uniquement quand la proposition ne fournit pas de loyer)
  const [manualMonthlyRent, setManualMonthlyRent] = useState<string>(
    contract.monthly_rent_ht != null ? String(contract.monthly_rent_ht) : ''
  );
  const [manualQuarterlyRent, setManualQuarterlyRent] = useState<string>(
    contract.quarterly_rent_ht != null ? String(contract.quarterly_rent_ht) : ''
  );

  const [uploading, setUploading] = useState(false);
  const [downloadingProposal, setDownloadingProposal] = useState(false);
  const [previewingProposal, setPreviewingProposal] = useState(false);
  const [generatingContractPdf, setGeneratingContractPdf] = useState(false);

  const endDate = implementationDate && durationMonths
    ? addMonths(implementationDate, parseInt(durationMonths))
    : null;

  // Source unique du loyer : proposition validée → sinon valeur manuelle → sinon null
  const manualRentNumber = manualMonthlyRent.trim() === '' ? null : Number(manualMonthlyRent);
  const manualQuarterlyNumber = manualQuarterlyRent.trim() === '' ? null : Number(manualQuarterlyRent);
  const proposalMonthlyRent = !isQuick && proposalRent?.monthly != null ? proposalRent.monthly : null;
  const proposalQuarterlyRent = !isQuick && proposalRent?.quarterly != null ? proposalRent.quarterly : null;
  const validManualMonthlyRent = manualRentNumber != null && !Number.isNaN(manualRentNumber) ? manualRentNumber : null;
  const validManualQuarterlyRent = manualQuarterlyNumber != null && !Number.isNaN(manualQuarterlyNumber) ? manualQuarterlyNumber : null;
  const quickMonthlyBase = validManualMonthlyRent ?? contract.monthly_rent_ht ?? null;
  const quickQuarterlyBase = validManualQuarterlyRent ?? contract.quarterly_rent_ht ?? null;
  const monthlyRent: number | null = isQuick
    ? (quickMonthlyBase ?? (quickQuarterlyBase != null ? Math.round((quickQuarterlyBase / 3) * 100) / 100 : null))
    : (proposalMonthlyRent ?? validManualMonthlyRent ?? contract.monthly_rent_ht ?? null);
  const quarterlyRent: number | null = isQuick
    ? (quickQuarterlyBase ?? (quickMonthlyBase != null ? calculateLoyerTrimestriel(quickMonthlyBase) ?? Math.round(quickMonthlyBase * 3 * 100) / 100 : null))
    : (proposalQuarterlyRent ?? (monthlyRent != null ? calculateLoyerTrimestriel(monthlyRent) ?? monthlyRent * 3 : null));
  const displayedAmount = paymentFrequency === 'trimestriel' ? quarterlyRent : monthlyRent;
  const hasProposalRent = !isQuick && (proposalRent?.monthly != null || proposalRent?.quarterly != null);

  const sortedCommerciaux = [...commerciaux].sort((a, b) => a.nom.localeCompare(b.nom));

  // Tolérer les valeurs héritées : ajouter la valeur stockée si absente de la liste canonique
  const partnerOptions = financialPartner && !FINANCIAL_PARTNERS.includes(financialPartner)
    ? [...FINANCIAL_PARTNERS, financialPartner]
    : FINANCIAL_PARTNERS;

  const commercialOptions = !commercialId || sortedCommerciaux.some((c) => c.id === commercialId)
    ? sortedCommerciaux
    : [
        ...sortedCommerciaux,
        {
          id: commercialId,
          nom: commercialId === 'quick'
            ? `Contrat rapide${contract.commercial_name ? ` — ${contract.commercial_name}` : ''}`
            : (contract.commercial_name ?? commercialId),
        } as (typeof sortedCommerciaux)[number],
      ];

  async function handleSave() {
    const selected = commerciaux.find((c) => c.id === commercialId);
    const manualNumber = manualMonthlyRent.trim() === '' ? null : Number(manualMonthlyRent);
    const manualMonthlyValue = manualNumber != null && !Number.isNaN(manualNumber)
      ? Math.round(manualNumber * 100) / 100
      : null;
    const manualQNumber = manualQuarterlyRent.trim() === '' ? null : Number(manualQuarterlyRent);
    const manualQuarterlyValue = manualQNumber != null && !Number.isNaN(manualQNumber)
      ? Math.round(manualQNumber * 100) / 100
      : null;
    const savedClientName = clientName.trim() || 'Nouveau contrat';
    const shouldRefreshQuickPlaceholderNumber =
      isServiceContract &&
      isQuick &&
      contract.client_name === 'Nouveau contrat' &&
      savedClientName !== contract.client_name &&
      contractNumber.trim() === (contract.contract_number ?? '');
    let nextContractNumber = contractNumber.trim() || null;

    try {
      if (isServiceContract && (!nextContractNumber || shouldRefreshQuickPlaceholderNumber)) {
        nextContractNumber = await generateServiceContractNumber(savedClientName, new Date(), contract.id);
        if (nextContractNumber) setContractNumber(nextContractNumber);
      }
    } catch (err) {
      toast({ title: 'Numérotation indisponible', description: (err as Error).message, variant: 'destructive' });
      return;
    }

    updateContract.mutate({
      id: contract.id,
      updates: {
        client_name: savedClientName,
        implementation_month: implementationDate ? format(implementationDate, 'yyyy-MM-dd') : null,
        financial_partner: hideFinancialPartner ? contract.financial_partner ?? null : (financialPartner || null),
        duration_months: durationMonths ? parseInt(durationMonths) : null,
        payment_frequency: paymentFrequency,
        commercial_id: isQuick ? (commercialId || 'quick') : (commercialId || contract.commercial_id),
        commercial_name: selected?.nom ?? (isQuick ? null : contract.commercial_name),
        contract_number: nextContractNumber,
        erp_reference: isServiceContract ? (erpReference.trim() || null) : contract.erp_reference ?? null,
        monthly_rent_ht: hasProposalRent ? contract.monthly_rent_ht ?? null : manualMonthlyValue,
        quarterly_rent_ht: hasProposalRent ? contract.quarterly_rent_ht ?? null : manualQuarterlyValue,
        cession_percent: hideFinancialPartner ? contract.cession_percent ?? null : cessionPercent,
        external_providers: isServiceContract ? externalProviders : contract.external_providers ?? [],
      },
    });
  }

  function addExternalProvider() {
    setExternalProviders((current) => [...current, { id: uid(), name: '', role: '', contact: '' }]);
  }

  function updateExternalProvider(id: string | undefined, patch: Partial<ContractExternalProvider>) {
    if (!id) return;
    setExternalProviders((current) => current.map((provider) => (provider.id === id ? { ...provider, ...patch } : provider)));
  }

  function removeExternalProvider(id: string | undefined) {
    if (!id) return;
    setExternalProviders((current) => current.filter((provider) => provider.id !== id));
  }

  async function handlePreviewProposal() {
    if (!contract.proposal_id) return;
    setPreviewingProposal(true);
    try {
      const { data, error } = await supabase
        .from('proposal_exports')
        .select('pdf_html_content')
        .eq('id', contract.proposal_id)
        .single();
      if (error || !data?.pdf_html_content) {
        toast({ title: 'Proposition indisponible', description: "Le contenu de la proposition n'est plus disponible.", variant: 'destructive' });
        return;
      }
      const previewWindow = window.open('', '_blank');
      if (!previewWindow) {
        toast({ title: 'Fenêtre bloquée', description: 'Autorisez les pop-ups pour visualiser la proposition.', variant: 'destructive' });
        return;
      }
      previewWindow.document.open();
      previewWindow.document.write(data.pdf_html_content);
      previewWindow.document.close();
    } catch {
      toast({ title: 'Erreur', description: "Impossible de récupérer la proposition.", variant: 'destructive' });
    } finally {
      setPreviewingProposal(false);
    }
  }

  async function handleDownloadProposal() {

    if (!contract.proposal_id) return;
    setDownloadingProposal(true);
    try {
      const { data, error } = await supabase
        .from('proposal_exports')
        .select('pdf_html_content')
        .eq('id', contract.proposal_id)
        .single();
      if (error || !data?.pdf_html_content) {
        toast({ title: 'Proposition indisponible', description: "Le contenu de la proposition n'est plus disponible.", variant: 'destructive' });
        return;
      }
      const printWindow = window.open('', '_blank');
      if (!printWindow) {
        toast({ title: 'Fenêtre bloquée', description: 'Autorisez les pop-ups pour télécharger la proposition.', variant: 'destructive' });
        return;
      }
      printWindow.document.open();
      printWindow.document.write(data.pdf_html_content);
      printWindow.document.close();
      printWindow.addEventListener('load', () => {
        setTimeout(() => printWindow.print(), 300);
      });
    } catch {
      toast({ title: 'Erreur', description: "Impossible de récupérer la proposition.", variant: 'destructive' });
    } finally {
      setDownloadingProposal(false);
    }
  }

  async function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    e.target.value = '';
    if (!file) return;
    if (file.type !== 'application/pdf' && !file.name.toLowerCase().endsWith('.pdf')) {
      toast({ title: 'Format invalide', description: 'Seuls les fichiers PDF sont acceptés.', variant: 'destructive' });
      return;
    }
    if (file.size > MAX_ATTACHMENT_SIZE) {
      toast({ title: 'Fichier trop volumineux', description: 'Taille maximale : 20 Mo.', variant: 'destructive' });
      return;
    }
    setUploading(true);
    try {
      // Remove previous attachment if any
      if (attachmentUrl) {
        await supabase.storage.from('contract-attachments').remove([attachmentUrl]);
      }
      const path = `contracts/${contract.id}/${Date.now()}-${sanitizeFileName(file.name)}`;
      const { error: upErr } = await supabase.storage
        .from('contract-attachments')
        .upload(path, file, { contentType: 'application/pdf', upsert: false });
      if (upErr) throw upErr;
      updateContract.mutate({
        id: contract.id,
        updates: { attachment_url: path, attachment_name: file.name },
      });
      setAttachmentState({ url: path, name: file.name });
    } catch (err) {
      toast({ title: 'Erreur upload', description: (err as Error).message, variant: 'destructive' });
    } finally {
      setUploading(false);
    }
  }

  async function handleAttachmentFile(mode: 'preview' | 'download', path = attachmentUrl, fileName = attachmentName) {
    if (!path) return;
    const { data, error } = await supabase.storage
      .from('contract-attachments')
      .download(path);
    if (error || !data) {
      toast({ title: 'Erreur', description: "Impossible de récupérer le PDF.", variant: 'destructive' });
      return;
    }
    const blobUrl = URL.createObjectURL(data);
    if (mode === 'preview') {
      const opened = window.open(blobUrl, '_blank');
      if (!opened) {
        URL.revokeObjectURL(blobUrl);
        toast({ title: 'Fenêtre bloquée', description: 'Autorisez les pop-ups pour visualiser le PDF.', variant: 'destructive' });
        return;
      }
      setTimeout(() => URL.revokeObjectURL(blobUrl), 60_000);
      return;
    }
    const link = document.createElement('a');
    link.href = blobUrl;
    link.download = fileName ?? path.split('/').pop() ?? 'contrat.pdf';
    document.body.appendChild(link);
    link.click();
    link.remove();
    setTimeout(() => URL.revokeObjectURL(blobUrl), 1_000);
  }

  // Le téléchargement passe systématiquement par un blob local : les URLs signées
  // pointent vers un domaine tiers souvent bloqué par les extensions (ERR_BLOCKED_BY_CLIENT).
  async function handleSignedAttachment(path = attachmentUrl) {
    await handleAttachmentFile('preview', path);
  }

  async function handleDownloadAttachment(path = attachmentUrl) {
    await handleAttachmentFile('download', path);
  }


  async function handleRemoveAttachment() {
    if (!attachmentUrl) return;
    await supabase.storage.from('contract-attachments').remove([attachmentUrl]);
    updateContract.mutate({
      id: contract.id,
      updates: { attachment_url: null, attachment_name: null },
    });
    setAttachmentState({ url: null, name: null });
  }

  async function handleOpenServiceContractPdf(mode: 'preview' | 'download') {
    if (canReuseAttachment) {
      await handleAttachmentFile(mode, attachmentUrl);
      return;
    }
    if (!contract.proposal_id) {
      toast({ title: 'Contrat indisponible', description: 'Aucune proposition source ne permet de générer le contrat.', variant: 'destructive' });
      return;
    }
    setGeneratingContractPdf(true);
    try {
      const uploaded = await generateAndUploadServiceContractPdf({
        proposalId: contract.proposal_id,
        contractId: contract.id,
        clientName: contract.client_name,
      });
      if (!uploaded) {
        toast({ title: 'Contrat indisponible', description: 'Le PDF contrat n’a pas pu être généré.', variant: 'destructive' });
        return;
      }
      const { error } = await supabase
        .from('contracts')
        .update({ attachment_url: uploaded.path, attachment_name: uploaded.name })
        .eq('id', contract.id);
      if (error) throw error;
      setAttachmentState({ url: uploaded.path, name: uploaded.name });
      await queryClient.invalidateQueries({ queryKey: ['contracts'] });
      if (attachmentUrl && attachmentUrl !== uploaded.path) {
        await supabase.storage.from('contract-attachments').remove([attachmentUrl]);
      }
      await handleAttachmentFile(mode, uploaded.path, uploaded.name);
    } catch (err) {
      toast({ title: 'Erreur', description: (err as Error).message || 'Impossible de générer le contrat.', variant: 'destructive' });
    } finally {
      setGeneratingContractPdf(false);
    }
  }

  return (
    <div className="border border-border rounded-lg bg-card overflow-hidden">
      <div
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center gap-3 px-4 py-3 hover:bg-muted/40 transition-colors text-left cursor-pointer"
        role="button"
        tabIndex={0}
      >
        <div className="min-w-0 space-y-1">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="font-medium text-sm">{contract.client_name}</span>
            {contract.contract_number && (
              <Badge variant="secondary" className="font-mono text-[10px]">N° {contract.contract_number}</Badge>
            )}
            {isQuick && (
              <Badge variant="outline" className="text-[10px] uppercase tracking-wide">Contrat rapide</Badge>
            )}
            {isClosed && (
              <Badge variant="outline" className="gap-1 text-[10px] border-amber-500/40 text-amber-700">
                <Archive className="h-3 w-3" />
                Clôturé le {format(parseISO(contract.closed_at as string), 'dd/MM/yyyy', { locale: fr })}
              </Badge>
            )}
            {!isClosed && renewing && (
              <Badge variant="warning" className="gap-1">
                <Bell className="h-3 w-3" />
                Renouvellement dans {monthsLeft}m
              </Badge>
            )}
          </div>
          <div className="flex items-center gap-3 flex-wrap text-xs text-muted-foreground">
            <span className="flex items-center gap-1">
              <CalendarIcon className="h-3 w-3" />
              {contract.implementation_month
                ? format(parseISO(contract.implementation_month), 'dd/MM/yyyy', { locale: fr })
                : format(parseISO(contract.validated_at), 'dd/MM/yyyy', { locale: fr })}
            </span>
            {monthlyRent != null && (
              <span className="flex items-center gap-1">
                <span className={cn(paymentFrequency === 'mensuel' && 'text-primary font-semibold')}>
                  Mensuel {monthlyRent.toLocaleString('fr-FR', { minimumFractionDigits: 2 })} €
                </span>
                <span>·</span>
                <span className={cn(paymentFrequency === 'trimestriel' && 'text-primary font-semibold')}>
                  Trimestriel {(quarterlyRent ?? 0).toLocaleString('fr-FR', { minimumFractionDigits: 2 })} €
                </span>
              </span>
            )}
            {!hideFinancialPartner && contract.financial_partner && <span>{contract.financial_partner}</span>}
            {contract.duration_months && <span className="flex items-center gap-1"><Clock className="h-3 w-3" />{contract.duration_months} mois</span>}
            {endDate && <span>→ {format(endDate, 'MM/yyyy', { locale: fr })}</span>}
            {!hideFinancialPartner && contract.cession_percent != null && (
              <span className="flex items-center gap-1">Cession {contract.cession_percent} %</span>
            )}
            {attachmentUrl && attachmentName?.toLowerCase().endsWith('.pdf') && <span className="flex items-center gap-1"><FileText className="h-3 w-3" />PDF joint</span>}
          </div>
          {(contract.template_name || isQuick) && (
            <div className="text-[11px] text-muted-foreground">{contract.template_name ?? 'Contrat rapide'}</div>
          )}
        </div>
        <div className="flex items-center gap-1 flex-shrink-0">
          {isQuick ? (
            <>
              <Button
                variant="ghost"
                size="icon"
                className="h-8 w-8 text-blue-500 hover:text-blue-700 hover:bg-blue-50 flex-shrink-0 disabled:opacity-40"
                title={attachmentUrl ? 'Visualiser le PDF joint' : 'Aucune proposition ni PDF joint'}
                disabled={!attachmentUrl}
                onClick={(e) => { e.stopPropagation(); isServiceContract ? handleAttachmentFile('preview') : handleSignedAttachment(); }}
              >
                <Eye className="w-4 h-4" />
              </Button>
              <Button
                variant="ghost"
                size="icon"
                className="h-8 w-8 text-emerald-600 hover:text-emerald-700 hover:bg-emerald-50 flex-shrink-0 disabled:opacity-40"
                title={attachmentUrl ? 'Télécharger le PDF joint' : 'Aucune proposition ni PDF joint'}
                disabled={!attachmentUrl}
                onClick={(e) => { e.stopPropagation(); handleDownloadAttachment(); }}
              >
                <Download className="w-4 h-4" />
              </Button>
            </>
          ) : (
            <>
              {!isServiceContract && contract.proposal_id && attachmentUrl && (
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-8 w-8 text-violet-600 hover:text-violet-700 hover:bg-violet-50 flex-shrink-0"
                  title="Visualiser la proposition générée"
                  disabled={previewingProposal}
                  onClick={(e) => { e.stopPropagation(); handlePreviewProposal(); }}
                >
                  {previewingProposal ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileText className="w-4 h-4" />}
                </Button>
              )}

              <Button
                variant="ghost"
                size="icon"
                className="h-8 w-8 text-blue-500 hover:text-blue-700 hover:bg-blue-50 flex-shrink-0"
                title={isServiceContract ? 'Visualiser le contrat' : attachmentUrl ? 'Visualiser le contrat signé' : 'Visualiser la proposition'}
                disabled={generatingContractPdf}
                onClick={(e) => {
                  e.stopPropagation();
                  if (isServiceContract) handleOpenServiceContractPdf('preview');
                  else if (attachmentUrl) handleSignedAttachment();
                  else onVisualize?.(contract);
                }}
              >
                {generatingContractPdf ? <Loader2 className="w-4 h-4 animate-spin" /> : <Eye className="w-4 h-4" />}
              </Button>
              <Button
                variant="ghost"
                size="icon"
                className="h-8 w-8 text-emerald-600 hover:text-emerald-700 hover:bg-emerald-50 flex-shrink-0"
                title={isServiceContract ? 'Télécharger le contrat' : attachmentUrl ? 'Télécharger le contrat signé' : 'Télécharger la proposition'}
                disabled={downloadingProposal || generatingContractPdf}
                onClick={(e) => {
                  e.stopPropagation();
                  if (isServiceContract) handleOpenServiceContractPdf('download');
                  else if (attachmentUrl) handleDownloadAttachment();
                  else handleDownloadProposal();
                }}
              >
                {downloadingProposal || generatingContractPdf ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
              </Button>
            </>
          )}
          {canEditContract && (
            isClosed ? (
              <Button
                variant="ghost"
                size="icon"
                className="h-8 w-8 text-amber-600 hover:text-amber-700 hover:bg-amber-50 flex-shrink-0"
                title="Rouvrir le contrat"
                disabled={updateContract.isPending}
                onClick={(e) => { e.stopPropagation(); updateContract.mutate({ id: contract.id, updates: { closed_at: null } }); }}
              >
                <ArchiveRestore className="w-4 h-4" />
              </Button>
            ) : (
              <AlertDialog>
                <AlertDialogTrigger asChild>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="h-8 w-8 text-amber-600 hover:text-amber-700 hover:bg-amber-50 flex-shrink-0"
                    title="Clôturer le contrat"
                    onClick={(e) => e.stopPropagation()}
                  >
                    <Archive className="w-4 h-4" />
                  </Button>
                </AlertDialogTrigger>
                <AlertDialogContent>
                  <AlertDialogHeader>
                    <AlertDialogTitle>Clôturer le contrat ?</AlertDialogTitle>
                    <AlertDialogDescription>
                      Le contrat de <strong>{contract.client_name}</strong> sera déplacé dans « Contrats archivés » (accessible via le tri). Vous pourrez le rouvrir à tout moment.
                    </AlertDialogDescription>
                  </AlertDialogHeader>
                  <AlertDialogFooter>
                    <AlertDialogCancel>Annuler</AlertDialogCancel>
                    <AlertDialogAction
                      onClick={() => updateContract.mutate({ id: contract.id, updates: { closed_at: new Date().toISOString() } })}
                      disabled={updateContract.isPending}
                    >
                      Clôturer
                    </AlertDialogAction>
                  </AlertDialogFooter>
                </AlertDialogContent>
              </AlertDialog>
            )
          )}
          {canEditContract && (
            <AlertDialog>
              <AlertDialogTrigger asChild>
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-8 w-8 text-red-400 hover:text-red-600 hover:bg-red-50 flex-shrink-0"
                  title="Supprimer le contrat"
                  onClick={(e) => e.stopPropagation()}
                >
                  <Trash2 className="w-4 h-4" />
                </Button>
              </AlertDialogTrigger>
              <AlertDialogContent>
                <AlertDialogHeader>
                  <AlertDialogTitle>Supprimer le contrat ?</AlertDialogTitle>
                  <AlertDialogDescription>
                    Le contrat de <strong>{contract.client_name}</strong> sera définitivement supprimé. Cette action est irréversible.
                  </AlertDialogDescription>
                </AlertDialogHeader>
                <AlertDialogFooter>
                  <AlertDialogCancel>Annuler</AlertDialogCancel>
                  <AlertDialogAction
                    onClick={() => deleteContract.mutate(contract.id)}
                    disabled={deleteContract.isPending}
                    className="bg-red-600 hover:bg-red-700 text-white"
                  >
                    {deleteContract.isPending ? 'Suppression…' : 'Supprimer'}
                  </AlertDialogAction>
                </AlertDialogFooter>
              </AlertDialogContent>
            </AlertDialog>
          )}
          <div className="text-muted-foreground">
            {expanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
          </div>
        </div>
      </div>

      {expanded && (
        <div className="border-t border-border bg-muted/20 p-4 space-y-4">
          <div className="space-y-1.5">
            <Label className="text-xs">Client</Label>
            {canEditContract ? (
              <Input
                value={clientName}
                onChange={(e) => setClientName(e.target.value)}
                placeholder="Nom du client"
                className="h-9 text-sm"
              />
            ) : (
              <div className="min-h-9 px-3 py-2 text-sm border border-border rounded-md bg-muted/40">
                {contract.client_name || '—'}
              </div>
            )}
          </div>
          {(() => {
            const allOptions = proposalOptions ?? [];
            const serviceOptions = allOptions.filter((o) => o.requiresIntervention !== false);

            const dur = parseInt(durationMonths) || 0;
            const computeTotalHt = (opts: typeof allOptions) => {
              let totalHt = 0;
              for (const opt of opts) {
                if (typeof opt.priceTotal === 'number') {
                  totalHt += opt.priceTotal;
                } else if (typeof opt.price === 'number' && dur > 0) {
                  totalHt += opt.price * dur;
                }
              }
              return totalHt;
            };
            const fmt = (n: number) => n.toLocaleString('fr-FR', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
            const priceLabelOf = (opt: typeof allOptions[number]) =>
              opt.showPrice === false
                ? null
                : (getOptionPriceLabel({
                    price: opt.price ?? null,
                    priceTotal: opt.priceTotal ?? null,
                    showPriceMode: opt.showPriceMode ?? 'mensuel',
                    pricingScope: 'par_machine',
                  }) ?? '').replace(/\s*\/machine/g, '').trim() || null;

            const totalBlockFor = (opts: typeof allOptions) => {
              const totalHt = computeTotalHt(opts);
              const monthlyHt = dur > 0 ? totalHt / dur : 0;
              return totalHt > 0 ? (
                <div className="mt-2 pt-2 border-t border-border/60 flex items-center justify-between text-sm">
                  <span className="font-semibold">Total Service HT</span>
                  <span className="font-semibold text-primary">
                    {fmt(totalHt)} € HT
                    {dur > 0 && (
                      <span className="ml-2 text-xs font-normal text-muted-foreground">
                        (soit {fmt(monthlyHt)} €/mois sur {dur} mois)
                      </span>
                    )}
                  </span>
                </div>
              ) : null;
            };

            if (isServiceContract) {
              const norm = (s: string) => s.trim().toLowerCase();
              const matchedLabels = new Set(serviceRefs.map((r) => norm(r.service_label)));
              const extraRows = allOptions
                .filter((opt) => !matchedLabels.has(norm(String(opt.name ?? ''))))
                .map((opt) => ({
                  name: String(opt.name ?? '—'),
                  erpReference: opt.erpReference ?? null,
                  priceLabel: priceLabelOf(opt),
                }));
              return (
                <div className="space-y-1.5">
                  <Label className="text-xs">Services & interventions</Label>
                  <div className="rounded-md border border-border bg-background/60 p-3">
                    <ServiceReferencesPanel
                      contractId={contract.id}
                      clientName={contract.client_name}
                      isAdmin={isAdmin || isTechnicien}
                      refs={serviceRefs}
                      onPlanIntervention={onPlanIntervention}
                      priceLabelFor={(label) => {
                        const opt = allOptions.find((o) => norm(String(o.name ?? '')) === norm(label));
                        return opt ? priceLabelOf(opt) : null;
                      }}
                      extraRows={extraRows}
                      allowAdd
                      footer={totalBlockFor(allOptions)}
                      emptyMessage="Aucun service rattaché à ce contrat pour l'instant."
                    />
                  </div>
                </div>
              );
            }

            if (serviceOptions.length === 0) return null;
            return (
              <div className="space-y-1.5">
                <Label className="text-xs">Services & options de la proposition</Label>
                <div className="rounded-md border border-border bg-background/60 p-3 space-y-1.5">
                  {serviceOptions.map((opt, idx) => {
                    const label = priceLabelOf(opt) ?? '';
                    return (
                      <div key={idx} className="flex items-center justify-between gap-3 text-sm">
                        <div className="flex items-center gap-2 min-w-0 flex-1">
                          <span className="font-medium truncate">• {opt.name}</span>
                          <span
                            className={`inline-flex items-center rounded-md border px-1.5 py-0.5 text-[10px] font-medium whitespace-nowrap ${
                              opt.erpReference
                                ? 'bg-blue-100 text-blue-900 border-transparent'
                                : 'bg-muted text-muted-foreground border-transparent'
                            }`}
                            title="Référence ERP JAJA"
                          >
                            JAJA : {opt.erpReference || 'non renseigné'}
                          </span>
                        </div>
                        {label && <span className="text-xs font-semibold text-muted-foreground whitespace-nowrap">{label}</span>}
                      </div>
                    );
                  })}
                  {totalBlockFor(serviceOptions)}
                </div>
              </div>
            );
          })()}



          {!canEditContract && (
            <div className="grid grid-cols-1 md:grid-cols-3 gap-3 text-xs">
              <div className="space-y-0.5">
                <Label className="text-xs">Numéro de contrat</Label>
                <div className="text-sm">{contract.contract_number || '—'}</div>
              </div>
              <div className="space-y-0.5">
                <Label className="text-xs">Durée</Label>
                <div className="text-sm">{contract.duration_months ? `${contract.duration_months} mois` : '—'}</div>
              </div>
              <div className="space-y-0.5">
                <Label className="text-xs">Date de mise en place</Label>
                <div className="text-sm">
                  {contract.implementation_month
                    ? format(parseISO(contract.implementation_month), 'dd/MM/yyyy', { locale: fr })
                    : '—'}
                </div>
              </div>
              <div className="space-y-0.5">
                <Label className="text-xs">Commercial en charge</Label>
                <div className="text-sm">{contract.commercial_name || contract.commercial_id || '—'}</div>
              </div>
              <div className="space-y-0.5">
                <Label className="text-xs">Périodicité</Label>
                <div className="text-sm capitalize">{contract.payment_frequency ?? 'mensuel'}</div>
              </div>
            </div>
           )}

          {isServiceContract && proposalOpContact && (
            <div className="space-y-1.5">
              <Label className="text-xs">Contact opérationnel</Label>
              <div className="rounded-md border border-border bg-background/60 p-3 grid grid-cols-1 md:grid-cols-2 gap-3">
                <div className="space-y-0.5">
                  <Label className="text-[11px] text-muted-foreground">Prénom</Label>
                  <div className="text-sm">{proposalOpContact.firstName || '—'}</div>
                </div>
                <div className="space-y-0.5">
                  <Label className="text-[11px] text-muted-foreground">Nom</Label>
                  <div className="text-sm">{proposalOpContact.name || '—'}</div>
                </div>
              </div>
            </div>
          )}



          {canEditContract && (<>
          {isServiceContract && (
            <div className="space-y-1.5">
              <div className="flex items-center justify-between gap-2">
                <Label className="text-xs">Prestataires extérieurs</Label>
                <Button type="button" variant="outline" size="sm" onClick={addExternalProvider} className="h-8 gap-1 text-xs">
                  <Plus className="h-3.5 w-3.5" /> Ajouter
                </Button>
              </div>
              <div className="rounded-md border border-border bg-background/60 p-3 space-y-3">
                {externalProviders.length === 0 ? (
                  <div className="text-xs text-muted-foreground">Aucun prestataire extérieur renseigné.</div>
                ) : (
                  externalProviders.map((provider, idx) => (
                    <div key={provider.id ?? idx} className="grid grid-cols-1 md:grid-cols-[1fr_1fr_1fr_auto] gap-2 items-end">
                      <div className="space-y-1">
                        <Label className="text-[11px] text-muted-foreground">Nom</Label>
                        <Input
                          value={provider.name ?? ''}
                          onChange={(e) => updateExternalProvider(provider.id, { name: e.target.value })}
                          placeholder="Nom du prestataire"
                          className="h-8 text-sm"
                        />
                      </div>
                      <div className="space-y-1">
                        <Label className="text-[11px] text-muted-foreground">Rôle</Label>
                        <Input
                          value={provider.role ?? ''}
                          onChange={(e) => updateExternalProvider(provider.id, { role: e.target.value })}
                          placeholder="Ex : maintenance"
                          className="h-8 text-sm"
                        />
                      </div>
                      <div className="space-y-1">
                        <Label className="text-[11px] text-muted-foreground">Contact</Label>
                        <Input
                          value={provider.contact ?? ''}
                          onChange={(e) => updateExternalProvider(provider.id, { contact: e.target.value })}
                          placeholder="Nom / téléphone / email"
                          className="h-8 text-sm"
                        />
                      </div>
                      <Button
                        type="button"
                        variant="ghost"
                        size="icon"
                        onClick={() => removeExternalProvider(provider.id)}
                        className="h-8 w-8 text-red-500 hover:text-red-700 hover:bg-red-50"
                        title="Supprimer le prestataire"
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </div>
                  ))
                )}
              </div>
            </div>
          )}



          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <div className="space-y-1.5">
              <Label className="text-xs">Commercial en charge</Label>
              <Select value={commercialId} onValueChange={setCommercialId}>
                <SelectTrigger className="h-9 text-sm">
                  <SelectValue placeholder="Sélectionner" />
                </SelectTrigger>
                <SelectContent>
                  {commercialOptions.map((c) => (
                    <SelectItem key={c.id} value={c.id}>{c.nom}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs">Numéro de contrat</Label>
              <Input
                value={contractNumber}
                onChange={(e) => setContractNumber(e.target.value)}
                placeholder="Ex : 2026-00123"
                className="h-9 text-sm"
              />
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs">{hasProposalRent ? 'Loyers HT (issus de la proposition)' : 'Loyers HT'}</Label>

              {hasProposalRent ? (
                <div className="min-h-9 px-3 py-2 text-sm border border-border rounded-md bg-muted/40 flex items-center gap-3 flex-wrap">
                  <span
                    className={cn(
                      'px-2 py-0.5 rounded flex items-center gap-1',
                      paymentFrequency === 'mensuel'
                        ? 'bg-primary/10 text-primary font-semibold'
                        : 'text-muted-foreground'
                    )}
                  >
                    Mensuel <strong>{(monthlyRent ?? 0).toLocaleString('fr-FR', { minimumFractionDigits: 2 })} €</strong>
                    {paymentFrequency === 'mensuel' && <Badge variant="secondary" className="ml-1 text-[9px]">Sélectionnée</Badge>}
                  </span>
                  <span className="text-muted-foreground">·</span>
                  <span
                    className={cn(
                      'px-2 py-0.5 rounded flex items-center gap-1',
                      paymentFrequency === 'trimestriel'
                        ? 'bg-primary/10 text-primary font-semibold'
                        : 'text-muted-foreground'
                    )}
                  >
                    Trimestriel <strong>{(quarterlyRent ?? 0).toLocaleString('fr-FR', { minimumFractionDigits: 2 })} €</strong>
                    {paymentFrequency === 'trimestriel' && <Badge variant="secondary" className="ml-1 text-[9px]">Sélectionnée</Badge>}
                  </span>
                </div>
              ) : (
                <div className="grid grid-cols-2 gap-2">
                  <Input
                    type="number"
                    step="0.01"
                    value={manualMonthlyRent}
                    onChange={(e) => setManualMonthlyRent(e.target.value)}
                    placeholder="Loyer mensuel HT"
                    className="h-9 text-sm"
                  />
                  <Input
                    type="number"
                    step="0.01"
                    value={manualQuarterlyRent}
                    onChange={(e) => setManualQuarterlyRent(e.target.value)}
                    placeholder="Loyer trimestriel HT"
                    className="h-9 text-sm"
                  />
                </div>
              )}
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs">Date de mise en place</Label>
              <Popover>
                <PopoverTrigger asChild>
                  <Button
                    type="button"
                    variant="outline"
                    className={cn(
                      'h-9 w-full justify-start text-left font-normal text-sm',
                      !implementationDate && 'text-muted-foreground'
                    )}
                  >
                    <CalendarIcon className="mr-2 h-4 w-4" />
                    {implementationDate
                      ? format(implementationDate, 'dd/MM/yyyy', { locale: fr })
                      : 'Choisir une date'}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar
                    mode="single"
                    selected={implementationDate}
                    onSelect={setImplementationDate}
                    initialFocus
                    locale={fr}
                    className={cn('p-3 pointer-events-auto')}
                  />
                </PopoverContent>
              </Popover>
            </div>
            {!hideFinancialPartner && (
            <div className="space-y-1.5">
              <Label className="text-xs">Partenaire financier</Label>
              <Select value={financialPartner} onValueChange={setFinancialPartner}>
                <SelectTrigger className="h-9 text-sm">
                  <SelectValue placeholder="Sélectionner" />
                </SelectTrigger>
                <SelectContent>
                  {partnerOptions.map((p) => <SelectItem key={p} value={p}>{p}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            )}
            <div className="space-y-1.5">
              <Label className="text-xs">Durée (mois)</Label>
              <div className="flex items-center gap-2">
                <Select
                  value={DURATIONS.includes(Number(durationMonths)) ? durationMonths : ''}
                  onValueChange={setDurationMonths}
                >
                  <SelectTrigger className="h-9 text-sm flex-1">
                    <SelectValue placeholder="Sélectionner" />
                  </SelectTrigger>
                  <SelectContent>
                    {DURATIONS.map((d) => <SelectItem key={d} value={String(d)}>{d} mois</SelectItem>)}
                  </SelectContent>
                </Select>
                <Input
                  type="number"
                  min={1}
                  value={durationMonths}
                  onChange={(e) => setDurationMonths(e.target.value)}
                  placeholder="Autre"
                  className="w-24 h-9 text-sm"
                />
              </div>
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs">Périodicité</Label>
              <div className="flex gap-2">
                {(['mensuel', 'trimestriel'] as PaymentFrequency[]).map((f) => (
                  <button
                    key={f}
                    type="button"
                    onClick={() => setPaymentFrequency(f)}
                    className={cn(
                      'h-9 px-4 rounded-full text-sm font-medium border transition-colors capitalize',
                      paymentFrequency === f
                        ? 'bg-black text-white border-black'
                        : 'bg-background text-foreground border-border hover:bg-muted'
                    )}
                  >
                    {f}
                  </button>
                ))}
              </div>
            </div>
            {!hideFinancialPartner && (
              <div className="space-y-1.5">
                <Label className="text-xs">Cession</Label>
                <div className="flex gap-2 flex-wrap">
                  {([1, 2, 3, 4] as const).map((pct) => (
                    <button
                      key={pct}
                      type="button"
                      onClick={() => setCessionPercent(cessionPercent === pct ? null : pct)}
                      className={cn(
                        'h-9 px-4 rounded-full text-sm font-medium border transition-colors',
                        cessionPercent === pct
                          ? 'bg-black text-white border-black'
                          : 'bg-background text-foreground border-border hover:bg-muted'
                      )}
                    >
                      {pct} %
                    </button>
                  ))}
                  {cessionPercent !== null && (
                    <button
                      type="button"
                      onClick={() => setCessionPercent(null)}
                      className="h-9 px-3 rounded-full text-xs font-medium border border-border text-muted-foreground hover:bg-muted"
                    >
                      Aucune
                    </button>
                  )}
                </div>
              </div>
            )}
          </div>


          {/* Attachment section */}
          <div className="space-y-1.5">
            <Label className="text-xs">Pièce jointe (PDF)</Label>
            <input
              ref={fileInputRef}
              type="file"
              accept="application/pdf"
              className="hidden"
              onChange={handleFileChange}
            />
            {attachmentUrl ? (
              <div className="flex items-center gap-2 flex-wrap p-2 border border-border rounded-md bg-background">
                <FileText className="h-4 w-4 text-muted-foreground" />
                <span className="text-sm truncate flex-1 min-w-0">{attachmentName ?? 'Fichier PDF'}</span>
                <Button variant="outline" size="sm" onClick={() => handleDownloadAttachment()} className="gap-1">
                  <Download className="h-3.5 w-3.5" /> Télécharger
                </Button>
                <Button variant="outline" size="sm" onClick={() => fileInputRef.current?.click()} disabled={uploading} className="gap-1">
                  <Upload className="h-3.5 w-3.5" /> Remplacer
                </Button>
                <Button variant="outline" size="sm" onClick={handleRemoveAttachment} className="gap-1 text-red-600 hover:text-red-700">
                  <X className="h-3.5 w-3.5" /> Supprimer
                </Button>
              </div>
            ) : (
              <Button variant="outline" size="sm" onClick={() => fileInputRef.current?.click()} disabled={uploading} className="gap-1">
                {uploading ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Upload className="h-3.5 w-3.5" />}
                Importer un PDF
              </Button>
            )}
          </div>

          {endDate && (
            <div className="text-xs text-muted-foreground">
              Date de fin estimée : <strong>{format(endDate, 'MMMM yyyy', { locale: fr })}</strong>
            </div>
          )}
          <div className="flex justify-end">
            <Button size="sm" onClick={handleSave} disabled={updateContract.isPending}>
              {updateContract.isPending ? 'Enregistrement...' : 'Enregistrer'}
            </Button>
          </div>
          </>)}
        </div>
      )}
    </div>
  );
}
